# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/sul-dlss/rialto-trigger-rebuild
    steps:
      - checkout
      - run: go get github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: go test -v ./...
      - run: GOOS=linux go build -o trigger-rebuild

  register_image:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/sul-dlss/rialto-trigger-rebuild
    steps:
      - setup_remote_docker:
          version: 18.05.0-ce
      - checkout
      - run:
          name: Build Image & Register Task
          command: |
            docker build -t suldlss/rialto-trigger-rebuild:latest .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push suldlss/rialto-trigger-rebuild:latest

workflows:
  version: 2

  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  
  register_image:
    jobs:
      - register_image:
          filters:
            branches:
              only: master
